version: '3.8'

services:
  minerva:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: minerva
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    restart: unless-stopped
