version: '3.8'

services:
  minerva:
    build:
      context: ../src
    container_name: minerva
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    env_file:
      - ../config/secrets.env
    restart: unless-stopped
